config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
    
  get 'home/top'
  root to: "home#top"
  get 'home/about'
  resources :users, only: [:show, :edit, :index, :update]
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  resources :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true,
                   length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }                  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
   end

  # If you have extra params to permit, append them to the sanitizer.
   def configure_account_update_params
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
   end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
      @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
       redirect_to user_path(current_user.id)
    end
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end
  def update
    @user = User.find(params[:id])
    if 
      @user.update(user_params)
       flash[:notice] = "You have updated user successfully"
       redirect_to user_path(@user.id)
    else 
      render :edit
    end   
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <%= @user.errors.count %>errors prohibited this obj from being saved:Title can't be blank	
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-lg-4">
			<h1>User info</h1>

			<%= form_for(@user) do |f| %>

			<span>Name <%= f.text_field :name, autofocus: true %></span><br>

			<p>Image</p>
			<p><%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %></p>

			<p>
				<span>Introduction <%= f.text_area :introduction %></span>
			</p>

			<%= f.submit "Update User" %>

			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <div class="user-profile-image">
       <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    </div>

    <table class="table">
					
					<tbody>
						<tr>
							<th>name</th>
							<th><%= @current_user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</tbody>


		</table>

    
    <%= link_to "", edit_user_path(@user.id), class:"btn btn-default col-xs-12 glyphicon glyphicon-wrench" %>
    
    
    
    <h2>New book</h2>
    <%= form_for(@book) do |f| %>
    　<% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li> 
          <% end %>
      <% end %> 　
    
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <button class="btn btn-primary col-xs-12">Create Book</button>
        
    
    <% end %>
  </div>





  <div class="col-xs-9">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <td>image</td>
          <td>name</td>
          <td></td>
        </tr>
      </thead>
      <tbody> 
       <% @users.each do |user| %> 
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
       <% end %> 
      </tbody>  
    </table>  
  </div>



 </div>  
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
  
  <div class="col-xs-3">
    <h2>User info</h2>
    <div class="user-profile-image">
       <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    </div>

    <table class="table">
					
					<tbody>
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</tbody>


		</table>

    
    <%= link_to "", edit_user_path(@user.id), class:"btn btn-default col-xs-12 glyphicon glyphicon-wrench" %>
    
    
    
    <h2>New book</h2>
    <%= form_for(@book) do |f| %>
    　<% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li> 
          <% end %>
      <% end %> 　
    
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <button class="btn btn-primary col-xs-12">Create Book</button>
    
    <% end %>
  </div>
  
  
  
  <div class="col-xs-9">
    <h2>Book</h2>
    <table class="table">
      <thead>
        <tr>
          <td></td>
          <td>Title</td>
          <td>Opinion</td>
        </tr>
      </thead>
      <tbody> 
       <% @books.each do |book| %> 
        <tr>
          <td><%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
       <% end %>   
      </tbody>  
    </table>  
  </div>


  </div>  

</div>