config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
    
  get 'home/top'
  root to: "home#top"
  get 'home/about'
  resources :users, only: [:show, :edit, :index, :update]
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  resources :books
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true,
                     length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end
  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end  
  end
  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
       flash[:notice] =  "You have created book successfully"
       redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end  
  end  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
       flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
      render :edit
    end     
  end
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private
   def book_params
    params.require(:book).permit(:title, :body)
   end  
   
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <%= @book.errors.count %>errors prohibited this obj from being saved:Title can't be blank	
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
	<div class="row">
		<div class="col-lg-6 col-lg-offset-3">
			<h1>Editing Book</h1>

			<%= flash[:notice] %>

			<%= form_for(@book) do |f| %>

			<h4>Title</h4>
			<%= f.text_field :title, class: "col-xs-12" %>

			<h4>Opinion</h4>
			<%= f.text_area :body, class: "col-xs-12 body-col" %><br>

			<button type="submit" class="btn btn-primary btn-block">Update Book</button>

			<% end %>
			
			
			<%= link_to "Show", book_path %>/<%= link_to "Back", books_path %>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <div class="user-profile-image">
       <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    </div>

    <table class="table">
					
					<tbody>
						<tr>
              <th>
              name
              <%= @user.name %>
              </th>
						</tr>
						<tr>
              <th>
              introduction
              <%= @user.introduction %>
              </th>
						</tr>
					</tbody>


		</table>

    
    <%= link_to "", edit_user_path(@user.id), class:"btn btn-default col-xs-12 glyphicon glyphicon-wrench" %>
    
    
    
    <h2>New book</h2>
    <%= form_for(@book) do |f| %>
    　<% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li> 
          <% end %>
      <% end %> 　
    
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <button class="btn btn-primary col-xs-12">Create Book</button>
        
    
    <% end %>
  </div>


  <div class="col-xs-9">
    <h2>Books</h2>
    <table class="table">
      <thead>
        <tr>
          <td></td>
          <td>Title</td>
          <td>Opinion</td>
        </tr>
      </thead>
      <tbody> 
       <tbody>
	        <% @books.each do |book| %>
	        	<tr>
	        		<td><%= link_to user_path(book.user.id) do %><%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "50x50" %><% end %></td>
	        		<td><%= link_to book.title, book_path(book.id) %></td>
	        		<td><%= book.body %></td>
	        	</tr>
	        <% end %>
      </tbody>  
    </table>  
  </div>

 </div> 
</div>

app/views/books/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-xs-3">
    <h2>User info</h2>
    <div class="user-profile-image">
       <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg" %>
    </div>

    <table class="table">
					
					<tbody>
						<tr>
							<th>name</th>
							<th><%= @user.name %></th>
						</tr>
						<tr>
							<th>introduction</th>
							<th><%= @user.introduction %></th>
						</tr>
					</tbody>


		</table>

    
    <%= link_to "", edit_user_path(@user.id), class:"btn btn-default col-xs-12 glyphicon glyphicon-wrench" %>
    
    
    
    <h2>New book</h2>
    <%= form_for(@book) do |f| %>
    　<% if @book.errors.any? %>
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li> 
          <% end %>
      <% end %> 　
    
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>

    <button class="btn btn-primary col-xs-12">Create Book</button>
        
    
    <% end %>
  </div>




  <div class="col-xs-9">
    <h2>Book detail</h2>
    <table class="table">
			<tr>
        <td>
          <%= link_to user_path(@user.id) do %>
          <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %><br><%= @user.name %><% end %>
        </td>
				  <td><%= link_to @book.title, book_path(@book.id) %></td>
				  <td><%= @book.body %></td>
				  <% if @user.id == current_user.id %>
				    <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
				    <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-danger", method: :delete, "data-confirm" => "本当に消しますか？" %>	</td>
				  <% end %>
			
			</tr>
		</table>
		</div>


 </div>
</div>