config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions:      'users/sessions',
        passwords:     'users/passwords',
        registrations: 'users/registrations'
    }
    
  get 'home/top'
  root to: "home#top"
  get 'home/about'
  resources :users, only: [:show, :edit, :index, :update]
  

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  resources :books
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
  <nav class="navbar navbar-default">
    <div class="nav-header">
			<div class="text navbar-left"><span>Bookers</span></div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
         <% if user_signed_in? %>
          <li><%= link_to "Home", user_path(current_user.id), class:"glyphicon glyphicon-home" %></li>
          <li><%= link_to "Users", users_path , class:"glyphicon glyphicon-user" %></li>
          <li><%= link_to "Books", books_path, class:"glyphicon glyphicon-book" %></li>
          <li><%= link_to "logout", destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-log-out" %></li>
         <% else %>
          <li><%= link_to "Home", root_path, class:"glyphicon glyphicon-home" %></li>
          <li><%= link_to "About", home_about_path, class:"glyphicon glyphicon-link" %></li>
          <li><%= link_to "sign up", new_user_registration_path, class:"glyphicon glyphicon-edit" %></li>
          <li><%= link_to "login", new_user_session_path, class:"glyphicon glyphicon-log-in" %></li>
         <% end %>
        </ul>
      </div>   
    </div>
  </nav>
  </div>
  

  <% if flash[:notice] %>
    <div class="notification is-info">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  
  <% if flash[:alert] %>
    <div class="notification is-dander">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>


    <%= yield %>
  </body>
</html>